- clean:
    - '~'
    - '~/.config'
    - '~/.config/i3'
    - '~/.config/i3status'

- link:
    ~/.config/fish: fish/
    ~/.config/i3/config:
        create: true
        path: i3/config
    ~/.config/i3status/config:
        create: true
        path: i3/i3status.conf
    ~/.config/nvim: nvim/
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.pam_environment: pam_environment
    ~/.tmux.conf: tmux.conf
    ~/.Xresources: Xresources

- shell:
  - git submodule update --init --recursive # Update submodules
  - mkdir -p ~/.local/share/lynx
