- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/fish'
    - '~/.config/fish/functions'
    - '~/.config/git'
    - '~/.config/kitty'
    - '~/.config/nvim'
    - '~/.config/systemd/user'
    - '~/.config/tinyfugue'
    - '~/.config/xfce4/terminal'
    - '~/.config/xfce4/xfconf/xfce-perchannel-xml'
    - '~/.gnupg'
    - '~/.local/bin'
    - '~/.local/share/konsole'

- link:
    ~/.ansible.cfg: ansible.cfg
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions/fish_greeting.fish: fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_prompt.fish: fish/functions/fish_prompt.fish
    ~/.config/fish/functions/fish_right_prompt.fish: fish/functions/fish_right_prompt.fish
    ~/.config/fish/functions/fish_title.fish: fish/functions/fish_title.fish
    ~/.config/fish/functions/fzman.fish: fish/functions/fzman.fish
    ~/.config/fish/functions/ssh.fish: fish/functions/ssh.fish
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/kitty/kitty.conf: kitty/kitty.conf
    ~/.config/kglobalshortcutsrc: kde/kglobalshortcutsrc
    ~/.config/khotkeysrc: kde/khotkeysrc
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftdetect: nvim/ftdetect/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/tinyfugue/config.tf: tinyfugue/config.tf
    ~/.config/xfce4/terminal/terminalrc:
        force: true
        path: xfce4/terminal/terminalrc
    ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml:
        force: true
        path: xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.local/bin/neovim-update.sh: bin/neovim-update.sh
    ~/.local/share/konsole/Gruvbox_dark.colorscheme: kde/konsole/Gruvbox_dark.colorscheme
    ~/.local/share/konsole/Kiba.profile: kde/konsole/Kiba.profile
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf

- shell:
    # Update git submodules
    - git submodule update --init --recursive
    # Install terminfo
    - |
        tic term/screen.terminfo
        tic term/screen-256color.terminfo
        tic term/tmux.terminfo
        tic term/tmux-256color.terminfo
        tic term/xterm.terminfo
        tic term/xterm-256color.terminfo
    # Update neovim
    - ~/.local/bin/neovim-update.sh
