- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/fish'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.config/tinyfugue'
    - '~/bin'

- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions: fish/functions/
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/tinyfugue/config.tf: tinyfugue/config.tf
    ~/.ansible.cfg: ansible.cfg
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf
    ~/bin/neovim-update.sh: bin/neovim-update.sh

- shell:
    # Update git submodules
    - git submodule update --init --recursive
    # Install terminfo
    - |
        tic term/screen.terminfo
        tic term/screen-256color.terminfo
        tic term/tmux.terminfo
        tic term/tmux-256color.terminfo
        tic term/xterm.terminfo
        tic term/xterm-256color.terminfo
    # Update neovim
    - ~/bin/neovim-update.sh
