- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/git'
    - '~/.config/nvim'

- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/fish_prompt.fish: fish/fish_prompt.fish
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/i3/config: i3/config
    ~/.config/i3status/config: i3status/config
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.conkyrc: conkyrc
    ~/.minttyrc: minttyrc
    ~/.profile: profile
    ~/.spectrwm.conf: spectrwm.conf
    ~/.tmux.conf: tmux.conf
    ~/.Xresources: Xresources

- shell:
    # Update git submodules
    - git submodule update --init --recursive

    # Install Neovim spelling dictionary and suggestions
    - mkdir -p ~/.config/nvim/spell
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.spl ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.spl
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.sug ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.sug
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug

    # Keep vim-plug updated and install or update neovim plugins
    - nvim -i NONE -c PlugClean! -c PlugUpdate -c quitall > /dev/null

