- clean:
    - '~'
    - '~/.config'
    - '~/.config/git'
    - '~/.config/nvim'

- link:
    ~/.config/fish/config.fish:
        create: true
        path: fish/config.fish
    ~/.config/git/config:
        create: true
        path: git/config
    ~/.config/git/ignore_global:
        create: true
        path: git/ignore_global
    ~/.config/nvim/init.vim:
        create: true
        path: nvim/init.vim
    ~/.config/nvim/ftplugin:
        create: true
        path: nvim/ftplugin/
    ~/.config/nvim/autoload:
        create: true
        path: nvim/autoload/
    ~/.pam_environment: pam_environment
    ~/.spectrwm.conf: spectrwm.conf
    ~/.tmux.conf: tmux.conf

- shell:
  - git submodule update --init --recursive # Update submodules
