- clean: ['~', '~/.config']

- link:
    ~/.config/fish: fish/
    ~/.config/i3: i3/
    ~/.config/nvim: nvim/
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.pam_environment: pam_environment
    ~/.tmux.conf: tmux.conf
    ~/.Xresources: Xresources

- shell:
  - git submodule update --init --recursive # Update submodules
  - mkdir -p ~/.local/share/lynx
