- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/aerc'
    - '~/.config/fish'
    - '~/.config/fish/functions'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.gnupg'
    - '~/.local/bin'
    - '~/.ssh'

- link:
    ~/.config/aerc/aerc.conf: aerc/aerc.conf
    ~/.config/aerc/binds.conf: aerc/binds.conf
    ~/.config/bat/batrc: bat/batrc
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions/__bobthefish_colors.fish: fish/functions/__bobthefish_colors.fish
    ~/.config/fish/functions/__bobthefish_display_colors.fish: fish/functions/__bobthefish_display_colors.fish
    ~/.config/fish/functions/__bobthefish_glyphs.fish: fish/functions/__bobthefish_glyphs.fish
    ~/.config/fish/functions/bobthefish_display_colors.fish: fish/functions/bobthefish_display_colors.fish
    ~/.config/fish/functions/dkr.fish: fish/functions/dkr.fish
    ~/.config/fish/functions/enc.fish: fish/functions/enc.fish
    ~/.config/fish/functions/fish_greeting.fish: fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_mode_prompt.fish: fish/functions/fish_mode_prompt.fish
    ~/.config/fish/functions/fish_prompt.fish: fish/functions/fish_prompt.fish
    ~/.config/fish/functions/fish_right_prompt.fish: fish/functions/fish_right_prompt.fish
    ~/.config/fish/functions/fish_ssh_agent.fish: fish/functions/fish_ssh_agent.fish
    ~/.config/fish/functions/fish_title.fish: fish/functions/fish_title.fish
    ~/.config/fish/functions/fzman.fish: fish/functions/fzman.fish
    ~/.config/fish/functions/ssh.fish: fish/functions/ssh.fish
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftdetect: nvim/ftdetect/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/ripgrep/rgrc: ripgrep/rgrc
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.local/bin/neovim-update.sh: bin/neovim-update.sh
    ~/.profile: profile
    ~/.ssh/config: ssh/config
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc

- shell:
    # Update git submodules
    - git submodule update --init --recursive
    # Install terminfo
    - ./bin/terminfo.sh
    # Update neovim
    - ~/.local/bin/neovim-update.sh
