- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/fish'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.config/termite'
    - '~/.config/tinyfugue'
    - '~/.nixpkgs'

- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions: fish/functions/
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/i3/config: i3/config
    ~/.config/i3status/config: i3status/config
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/termite/config: termite/config
    ~/.config/tinyfugue/config.tf: tinyfugue/config.tf
    ~/.conkyrc: conkyrc
    ~/.minttyrc: minttyrc
    ~/.nixpkgs/config.nix: nixpkgs/config.nix
    ~/.profile: profile
    ~/.spacemacs: spacemacs
    ~/.spectrwm.conf: spectrwm.conf
    ~/.tmux.conf: tmux.conf
    ~/.weechat/alias.conf: weechat/alias.conf
    ~/.weechat/aspell.conf: weechat/aspell.conf
    ~/.weechat/charset.conf: weechat/charset.conf
    ~/.weechat/exec.conf: weechat/exec.conf
    ~/.weechat/irc.conf: weechat/irc.conf
    ~/.weechat/logger.conf: weechat/logger.conf
    ~/.weechat/plugins.conf: weechat/plugins.conf
    ~/.weechat/relay.conf: weechat/relay.conf
    ~/.weechat/script.conf: weechat/script.conf
    ~/.weechat/sec.conf: weechat/sec.conf
    ~/.weechat/trigger.conf: weechat/trigger.conf
    ~/.weechat/weechat.conf: weechat/weechat.conf
    ~/.weechat/xfer.conf: weechat/xfer.conf
    ~/.Xresources: Xresources

- shell:
    # Update git submodules
    - git submodule update --init --recursive

    # Install Neovim spelling dictionary and suggestions
    - mkdir -p ~/.config/nvim/spell
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.spl ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.spl
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.sug ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.sug
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug

    # Keep vim-plug updated and install or update neovim plugins
    - nvim -i NONE -c PlugClean! -c PlugUpdate -c quitall > /dev/null

