- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/bat'
    - '~/.config/fish'
    - '~/.config/fish/functions'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.config/ripgrep'
    - '~/.gnupg'
    - '~/.local/bin'
    - '~/.ssh'

- link:
    ~/.config/bat/batrc: .config/bat/batrc
    ~/.config/fish/config.fish: .config/fish/config.fish
    ~/.config/fish/functions/dkr.fish: .config/fish/functions/dkr.fish
    ~/.config/fish/functions/enc.fish: .config/fish/functions/enc.fish
    ~/.config/fish/functions/fish_ssh_agent.fish: .config/fish/functions/fish_ssh_agent.fish
    ~/.config/fish/functions/fzman.fish: .config/fish/functions/fzman.fish
    ~/.config/fish/functions/ssh.fish: .config/fish/functions/ssh.fish
    ~/.config/git/config: .config/git/config
    ~/.config/git/ignore_global: .config/git/ignore_global
    ~/.config/nvim/autoload: .config/nvim/autoload/
    ~/.config/nvim/ftdetect: .config/nvim/ftdetect/
    ~/.config/nvim/ftplugin: .config/nvim/ftplugin/
    ~/.config/nvim/init.vim: .config/nvim/init.vim
    ~/.config/ripgrep/rgrc: .config/ripgrep/rgrc
    ~/.gnupg/gpg-agent.conf: .gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: .gnupg/gpg.conf
    ~/.local/bin/neovim-update.sh: .local/bin/neovim-update.sh
    ~/.profile: .profile
    ~/.ssh/config: .ssh/config
    ~/.tmux.conf: .tmux.conf
    ~/.vimrc: .vimrc

- shell:
    # Update git submodules
    - git submodule update --init --recursive
