- clean:
    - '~'
    - '~/.config'
    - '~/.config/git'
    - '~/.config/nvim'

- link:
    ~/.config/fish/config.fish:
        create: true
        path: fish/config.fish
    ~/.config/git/config:
        create: true
        path: git/config
    ~/.config/git/ignore_global:
        create: true
        path: git/ignore_global
    ~/.config/nvim/init.vim:
        create: true
        path: nvim/init.vim
    ~/.config/nvim/ftplugin:
        create: true
        path: nvim/ftplugin/
    ~/.config/nvim/autoload:
        create: true
        path: nvim/autoload/
    ~/.conkyrc: conkyrc
    ~/.profile: profile
    ~/.spectrwm.conf: spectrwm.conf
    ~/.tmux.conf: tmux.conf

- shell:
    # Update git submodules
    - git submodule update --init --recursive

    # Install Neovim spelling dictionary and suggestions
    - mkdir -p ~/.config/nvim/spell
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.spl ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.spl
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl
    - >
        [ -f ~/.config/nvim/spell/en.utf-8.sug ] ||
        curl -o ~/.config/nvim/spell/en.utf-8.sug
        ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug

    # Keep vim-plug updated and install or update neovim plugins
    - nvim -i NONE -c PlugClean! -c PlugUpgrade -c PlugUpdate -c quitall > /dev/null

