- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/fish'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.config/termite'
    - '~/.config/tinyfugue'
    - '~/.nixpkgs'
    - '~/bin'

- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions: fish/functions/
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/i3/config: i3/config
    ~/.config/i3status/config: i3status/config
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/termite/config: termite/config
    ~/.config/tinyfugue/config.tf: tinyfugue/config.tf
    ~/.conkyrc: conkyrc
    ~/.minttyrc: minttyrc
    ~/.nixpkgs/config.nix: nixpkgs/config.nix
    ~/.profile: profile
    ~/.spectrwm.conf: spectrwm.conf
    ~/.tmux/plugins/tpm: tmux/plugins/tpm
    ~/.tmux/minimal.tmuxtheme: tmux/minimal.tmuxtheme
    ~/.tmux.conf: tmux.conf
    ~/.weechat/alias.conf: weechat/alias.conf
    ~/.weechat/aspell.conf: weechat/aspell.conf
    ~/.weechat/charset.conf: weechat/charset.conf
    ~/.weechat/exec.conf: weechat/exec.conf
    ~/.weechat/irc.conf: weechat/irc.conf
    ~/.weechat/logger.conf: weechat/logger.conf
    ~/.weechat/plugins.conf: weechat/plugins.conf
    ~/.weechat/relay.conf: weechat/relay.conf
    ~/.weechat/script.conf: weechat/script.conf
    ~/.weechat/sec.conf: weechat/sec.conf
    ~/.weechat/trigger.conf: weechat/trigger.conf
    ~/.weechat/weechat.conf: weechat/weechat.conf
    ~/.weechat/xfer.conf: weechat/xfer.conf
    ~/.Xresources: Xresources
    ~/bin/clean-journal: bin/clean-journal
    ~/bin/clean-nix: bin/clean-nix

- shell:
    - |
        # Update git submodules
        git submodule update --init --recursive

    - |
        # Install terminfo
        tic term/tmux.terminfo
        tic term/tmux-256color.terminfo
        tic term/xterm.terminfo
        tic term/xterm-256color.terminfo

    - |
        # Install Neovim spelling dictionary and suggestions
        if type nvim > /dev/null 2>&1; then
          mkdir -p ~/.config/nvim/spell

          if ! [ -f ~/.config/nvim/spell/en.utf-8.spl ]; then
            curl -o ~/.config/nvim/spell/en.utf-8.spl \
              ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl
          fi

          if ! [ -f ~/.config/nvim/spell/en.utf-8.sug ]; then
            curl -o ~/.config/nvim/spell/en.utf-8.sug \
              ftp://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug
          fi
        fi

    - |
        # Keep vim-plug updated and install or update neovim plugins
        if type nvim > /dev/null 2>&1; then
          nvim -i NONE -c PlugClean! -c PlugUpdate -c quitall > /dev/null
        fi

    - |
        # Install python neovim interface
        if type nvim > /dev/null 2>&1 && type pip3 > /dev/null 2>&1; then
          pip3 install --upgrade neovim
        fi
        if type nvim > /dev/null 2>&1 && type pip2 > /dev/null 2>&1; then
          pip2 install --upgrade neovim
        fi
