- clean: ['~', '~/.config']

- link:
    ~/.config/nvim: nvim/
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.pam_environment: pam_environment

- shell:
  - git submodule update --init --recursive # Update submodules
