- defaults:
    link:
        create: true
        relink: true

- clean:
    - '~'
    - '~/.config'
    - '~/.config/fish'
    - '~/.config/fish/functions'
    - '~/.config/git'
    - '~/.config/nvim'
    - '~/.config/systemd/user'
    - '~/.config/tinyfugue'
    - '~/.gnupg'
    - '~/.local/bin'

- link:
    ~/.config/fish/config.fish: fish/config.fish
    ~/.config/fish/functions/dkr.fish: fish/functions/dkr.fish
    ~/.config/fish/functions/fish_greeting.fish: fish/functions/fish_greeting.fish
    ~/.config/fish/functions/fish_prompt.fish: fish/functions/fish_prompt.fish
    ~/.config/fish/functions/fish_right_prompt.fish: fish/functions/fish_right_prompt.fish
    ~/.config/fish/functions/fish_title.fish: fish/functions/fish_title.fish
    ~/.config/fish/functions/fzman.fish: fish/functions/fzman.fish
    ~/.config/fish/functions/ssh.fish: fish/functions/ssh.fish
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore_global
    ~/.config/nvim/autoload: nvim/autoload/
    ~/.config/nvim/ftdetect: nvim/ftdetect/
    ~/.config/nvim/ftplugin: nvim/ftplugin/
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/tinyfugue/config.tf: tinyfugue/config.tf
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.local/bin/neovim-update.sh: bin/neovim-update.sh
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc

- shell:
    # Update git submodules
    - git submodule update --init --recursive
    # Install terminfo
    - |
        tic term/screen.terminfo
        tic term/screen-256color.terminfo
        tic term/tmux.terminfo
        tic term/tmux-256color.terminfo
        tic term/xterm.terminfo
        tic term/xterm-256color.terminfo
    # Update neovim
    - ~/.local/bin/neovim-update.sh
